### ISSUE TITLE
Termninal client requires file access permission, and no explanation provided as of why.

### ISSUE THREAD

**Issue by weshatheleopard** [connectbot/assets#1]
Why??? It worked just fine for years without it.

**Comment by kruton** [comment]
This is just for the graphical assets. Please open an issue at https://github.com/connectbot/connectbot/issues/ for issues with the app.

**Comment by weshatheleopard** [comment]
FYI, https://connectbot.org/bugs/ says that "Play Store listing issues" are to be reported here. You might want to change that verbiage.

But, other than that, why the external storage? Do you have _that_ many graphical assets?

**Comment by kruton** [comment]
It's had that permission since before the last Play Store release, but since we changed the target SDK level to Donut, it prompts you about it. See [the DONUT SDK level documentation](https://developer.android.com/reference/android/os/Build.VERSION_CODES.html#DONUT). In fact, the [commit that added write SD card](https://github.com/connectbot/connectbot/commit/a3ca36dcb24e5611e18123dc22bc632852ac217f) was way back around ConnectBot 1.6.0.

At the time it was mostly because without it you couldn't do much with the local shell because the shell runs with the permissions that the app has. I suppose I could remove it since [in KitKat you can access your own SD card area](https://developer.android.com/reference/android/os/Build.VERSION_CODES.html#KITKAT) without permission. There would probably be a lot of people that complain that functionality is crippled, though.

**Comment by kruton** [comment]
I started a [poll on the fate of this permission](https://plus.google.com/b/116964084929843019106/116964084929843019106/posts/b2oZqCdoYoM). Feel free to vote on that.
